eatmap/urls.py
from django.urls import path
from . import views

app_name='eatmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.Search, name='search'),
    path('shop_info/<str:restid>/', views.ShopInfo, name='shop_info'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

gourmet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('eatmap.urls')),
]

eatmap/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category_l = models.CharField('業態カテゴリ', max_length=10, blank=False)
    name = models.CharField('業態名', max_length=30, blank=False)


    def __str__(self):
        return str(self.name)


class Pref(models.Model):
    pref = models.CharField('都道府県コード', max_length=6, blank=False)
    name = models.CharField('都道府県名', max_length=10, blank=False)

    def __str__(self):
        return str(self.name)



SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class Review(models.Model):

    shop_id = models.CharField('店舗ID', max_length=10, blank=False)
    shop_name = models.CharField('店舗名', max_length=200, blank=False)
    image_url = models.CharField('画像1URL', max_length=300, blank=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    comment = models.TextField(verbose_name='レビューコメント', blank=False)
    score = models.PositiveSmallIntegerField(verbose_name='レビュースコア', choices=SCORE_CHOICES, default='3')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('shop_id', 'user')


    def __str__(self):
        return str(self.shop_id)

    def get_percent(self):
        percent = round(self.score / 5 * 100)
        return percent

eatmap/forms.py
from django import forms
from .models import  Category, Pref, User, Review
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class SearchForm(forms.Form):

    selected_pref = forms.ModelChoiceField(
        label='都道府県',
        # 必須か必須でないか。
        required=False,
        queryset=Pref.objects,
    )

    selected_category = forms.ModelChoiceField(
        label='業態',
        required=False,
        queryset=Category.objects,
    )

    freeword = forms.CharField(min_length=2, max_length=100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_pref = self.fields['selected_pref']
        selected_category = self.fields['selected_category']




class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label



# レビュー
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']

eatmap/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from django.contrib.auth import login, authenticate
from .models import Pref, Category, Review
from .forms import SearchForm, SignUpForm, LoginForm, ReviewForm
from django.contrib.auth.views import LoginView, LogoutView
import json
import requests
from django.db.models import Avg
from django.contrib import messages





def get_keyid():
    return "d345b8b9b46b3476887742e30468a2bf"


class IndexView(TemplateView):
    template_name = 'eatmap/index.html'

    def get_context_data(self, *args, **kwargs):
        searchform = SearchForm()
        
        query = get_gnavi_data('','','PREF11','ディナー',15)
        res_list = rest_search(query)
        pickup_list = extract_restaurant_info(res_list)
        review_list = Review.objects.all()[:10]
        params = {
            'searchform': searchform,
            'pickup_list': pickup_list,
            'review_list': review_list,

            }
        return params


def Search(request):
    if request.method == 'GET':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            category_l = request.GET['category_l']
            pref = request.GET['pref']
            freeword = request.GET['freeword']
            query = get_gnavi_data("", category_l, pref, freeword, 10)
            res_list = rest_search(query)
            total_hit_count = len(res_list)
            # 4. 整形した情報をリスト形式で保存し、paramsの一要素として渡す
            restaurants_info = extract_restaurant_info(res_list)

    params = {
        'total_hit_count': total_hit_count,
        'restaurants_info': restaurants_info,
        }

    return render (request, 'eatmap/search.html', params)


def get_gnavi_data(id, category_l, pref, freeword, hit_per_page):
    keyid = get_keyid()
    # 一度に取得できる最大件数
    hit_per_page = hit_per_page
    # 店舗のid（グルナビ内で一意になっている）
    id = id
    # 大業態カテゴリ
    category_l = category_l
    #pref
    pref = pref
    #Freeword
    freeword = freeword
    #今回は関東地方のみ（コール回数を少なくするため）
    area = "AREA110"
    #パラメータ設定
    query = {"keyid": keyid, "id":id, "area":area, "pref":pref, "category_l":category_l,"hit_per_page":hit_per_page, "freeword":freeword}

    return query


def rest_search(query):
    res_list = []
    res = json.loads(requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/", params=query).text)
    # レスポンスがerror でない場合に処理を開始する
    if "error" not in res:
        # print(f'res------->{res}')
        res_list.extend(res["rest"])
    return res_list


def extract_restaurant_info(restaurants: 'restaurant response') -> 'restaurant list':
    restaurant_list = []
    for restaurant in restaurants:
        id = restaurant["id"]
        name = restaurant["name"]
        name_kana = restaurant["name_kana"]
        url = restaurant["url"]
        url_mobile = restaurant["url_mobile"]
        shop_image1 = restaurant["image_url"]["shop_image1"]
        shop_image2 = restaurant["image_url"]["shop_image2"]
        address = restaurant["address"]
        tel = restaurant["tel"]
        station_line = restaurant["access"]["line"]
        station = restaurant["access"]["station"]
        latitude = restaurant["latitude"]
        longitude = restaurant["longitude"]
        pr_long = restaurant["pr"]["pr_long"]

        restaurant_list.append([id, name, name_kana, url, url_mobile, shop_image1, shop_image2, address, tel, station_line, station, latitude, longitude, pr_long])
        # 確認用
        print(f'restaurnt_list--------->{restaurant_list}')

    return restaurant_list



# ショップの詳細
def ShopInfo(request, restid):
    keyid = get_keyid()
    id = restid
    query = get_gnavi_data(id, "", "", "", 1)
    res_list = rest_search(query)
    restaurants_info = extract_restaurant_info(res_list)

    # 以下を追加、編集　ここから
    review_count = Review.objects.filter(shop_id=restid).count()
    score_ave = Review.objects.filter(shop_id = restid).aggregate(Avg('score'))

    #print('score_ave--------------', score_ave)
    """
     ↑の出力
     score_ave-------------- {'score__avg': 4.0}
     辞書型になっている。
     """

    average = score_ave['score__avg']

    #print('average----------', average)
    """
    ↑の出力
    average---------- 4.0
    
    """


    if average:
        average_rate = average / 5 * 100
    else:
        average_rate = 0

    if request.method == 'GET':
        review_form = ReviewForm()
        review_list = Review.objects.filter(shop_id = restid)

    else:
        form = ReviewForm(data=request.POST)
        score = request.POST['score']
        comment = request.POST['comment']

        if form.is_valid():
            review = Review()
            review.shop_id = restid
            review.shop_name = restaurants_info[0][1]
            review.shop_kana = restaurants_info[0][2]
            review.shop_address = restaurants_info[0][7]
            review.image_url = restaurants_info[0][5]
            review.user = request.user
            review.score = score
            review.comment = comment

            is_exist = 0
            is_exist = Review.objects.filter(shop_id=review.shop_id).filter(user=review.user).count()

            if not is_exist == 0:
                messages.error(request, '既にレビューを投稿済みです。')
                return redirect('eatmap:shop_info', restid)
            else:
                review.save()
                messages.success(request, 'レビューを投稿しました。')  # 追加
                return redirect('eatmap:shop_info', restid)
        else:
            messages.error(request, 'エラーがあります。')  # 追加
            return redirect('eatmap:shop_info', restid)
        return render(request, 'eatmap/index.html', {})

    params = {
        'title': '店舗詳細',
        'review_count': review_count,
        'restaurants_info': restaurants_info,
        'review_form': review_form,
        'review_list': review_list,
        'average': average,
        'average_rate': average_rate,
        }

    return render (request, 'eatmap/shop_info.html', params)
    # 以下を追加、編集　ここまで



# ユーザーの新規登録
class SignUp(CreateView):
    form_class =  SignUpForm
    template_name = 'eatmap/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request,user)
            return redirect('eatmap:index')
        return render(request, 'eatmap/signup.html', {'form':form})


# ログイン
class Login(LoginView):
    form_class = LoginForm
    template_name = 'eatmap/login.html'


# ログアウト
class Logout(LogoutView):
    template_name = 'eatmap/logout.html'

eatmap/templates/eatmap/base.html
{% load static %}

<!doctype html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- オリジナルのCSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    {% block script%}{% endblock script %}
    {% block css%}{% endblock css %}
    <title>まっちグルメ</title>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'eatmap:index' %}">まっちグルメ</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'eatmap:index' %}">TOP<span class="sr-only">(current)</span></a>
              </li>
            </ul>

            <ul class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <li>
                <a class="nav-item nav-link" href="{% url 'eatmap:logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'eatmap:login' %}">ログイン</a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'eatmap:signup' %}">新規ユーザ登録</a>
              </li>
              {% endif %}
            </ul>

            <form method="GET" action="{% url 'eatmap:search' %}" name="searchform">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <select class="form-control nav-link" name="pref">
                        <option value="">都道府県</option>
                        {% for item in pref_list %}
                        <option value="{{item.pref}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                    </li>
                    <li class="nav-item">
                    <select class="form-control nav-link" name="category_l">
                        <option value="">カテゴリ</option>
                        {% for item in category_list %}
                        <option value="{{item.category_l}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                    </li>
                    <li class="nav-item">
                        <input class="form-control nav-link" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                    </li>
                    <span>　</span>
                    <li class="nav-item">
                        <button type="submit" class="btn common-btn">Search</button>
                    </li>
                </ul>
            </form>
        </div>
    </nav>
    <br>
    <!-- messages の表示はここから記述   -->
    {% if messages %}
    <div class="container" stype="margin-top:1rem;">
        <div class="message">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success" role="alert">
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">
                {% else %}
                    <div class="alert alert-info" role="alert">
                {% endif %}
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}


    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>tabenavi</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/4391/7c3eb00e-9f2a-407d-9705-eeba36fdb47a.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

eatmap/templates/eatmap/index.html
{% load static %}

<!doctype html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'eatmap:index' %}">まっちグルメ</a>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav">
            <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'eatmap:logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'eatmap:login' %}">ログイン</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'eatmap:signup' %}">新規ユーザ登録</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>

    <section class="search">
        <div id="top_carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'image/topimage1.jpg' %}" class="d-block w-100" height="500px" alt="今日はどこで食べようか？">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>今日はどこで食事しよう？</h1>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/topimage2.jpg' %}" class="d-block w-100" height="500px">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>リアルな口コミNo.1！</h1>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/topimage3.jpg' %}" class="d-block w-100" height="500px">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>行きたいお店の<br>リアルな評判は？</h1>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#top_carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#top_carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>

    <section class="search-sec">
        <div class="container">
            <form method="GET" action="{% url 'eatmap:search' %}" name="searchform">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <select class="form-control search-slt" name="pref">
                                    <option value="">都道府県</option>
                                    {% for item in pref_list %}
                                    <option value="{{item.pref}}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <select class="form-control search-slt" name="category_l">
                                <option value="">カテゴリ</option>
                                {% for item in category_list %}
                                <option value="{{item.category_l}}">{{ item.name }}</option>
                                {% endfor %}
                            </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <input class="form-control search-slt" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <button type="submit" class="btn search-btn">検索</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <div class="container">
        <h2 class="section-title">おすすめ</h2>
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for item in pickup_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{ item.5}}" alt="{{item.1}}">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.1}}</h5>
                            <p class="card-text">{{item.7}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'eatmap:shop_info' item.0 %}" class="btn common-btn">詳細を見る</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <br>
    <div class="container">
        <h2 class="section-title">最近のレビュー</h2>
        <div class="row">
            <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
                <div class="MultiCarousel-inner">
                    {% for item in review_list %}
                    <div class="item">
                        <div class="pad15">
                            <img src="{{ item.image_url }}" style="width: 100%;">
                            <p>{{ item.shop_name }}</p>
                            <p>「{{ item.comment }}」</p>
                            <a href="{% url 'eatmap:shop_info' item.shop_id %}" class="btn common-btn">詳細を見る</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <button class="btn btn-primary leftLst"><</button>
                <button class="btn btn-primary rightLst">></button>
            </div>
        </div>
    </div>

    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="col-md-12 text-center">
                    <div class="twitter">
                    　<a href="//twitter.com/share" class="twitter-share-button" data-text="おすすめグルメ情報" data-url="{{ request.build_absolute_uri }}" data-lang="ja" data-size="large">
                        Tweet
                        </a>
                    </div>
                </div>
                <br/><br/>
                <hr/>
                <p>まっちグルメ</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/4385/da4fdb59-83b0-4488-aeba-8bc8af038624.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>
            </div>
        </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

eatmap/templates/eatmap/login.html
{% extends 'eatmap/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">ログイン</h1>
        <br><hr><br>
        <form action="" method="POST">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <p>{{field.label }}</p>
                            {{field}}
                            {{field.errors}}
                        <hr>
                        {% endfor %}
                        <button type="submit" class="btn common-btn">ログイン</button>
                        <input type="hidden" name="next" value="{{next}}">
                        {% csrf_token %}
                    </div>
                </div>
            </div>
        </form>
        <Hr>
         <p>まだアカウントがない方は<a href="{% url 'eatmap:signup' %}">こちら</a></p>
    </div>
</div>
{% endblock %}

eatmap/templates/eatmap/logout.html
{% extends 'eatmap/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block script %}
{% endblock %}


{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">またのご利用お待ちしております。</h1>
        <br><br><br>
        <a href="{% url 'eatmap:login' %}">ログインページへ</a>
    </div>
</div>
{% endblock %}

eatmap/templates/eatmap/search.html
{% extends 'eatmap/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
    {% if restaurants_info %}
        <h3>{{ total_hit_count }}件あります。<small>最大10件表示</small></h3>
        <br><br>
        {% for item in restaurants_info %}
        <div class="col-md-12">
            <div class="section-outer-box">
                <div class="row">
                    <div class="col-xs-3 col-md-3">
                        <img src="{{ item.5 }}" alt="{{ item.1 }}" class="img-rounded img-responsive" width="150px" />
                    </div>
                    <div class="col-xs-9 col-md-9 section-box">
                        <h4>{{ item.1 }}　<a href="{% url 'eatmap:shop_info' item.0 %}" class="btn common-btn">詳細を見る</a></h4>
                        <p>{{ item.2 }}</p>
                        <p>{{ item.7 }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-lg-12">
                <p>該当するものはありません。</p>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

eatmap/templates/eatmap/signup.html
{% extends 'eatmap/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block content %}

<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">新規ユーザー登録</h1>
        <br><hr><br>
        <form action="" method="POST">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <p>{{ field.label}}</p>
                            {{ field }}
                            {{ field.errors }}
                            <hr>
                        {% endfor %}
                        <button type="submit" class="btn common-btn" >登録してログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% csrf_token %}

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}